import type { SymbolDefinition, SymbolProvider } from "../model.js";

const AWS4 = "mxgraph.aws4";

function resource(
  icon: string,
  fill = "#527FFF",
  stroke = "#ffffff",
): SymbolDefinition {
  return {
    role: "resource",
    drawio: {
      shape: `${AWS4}.resourceIcon`,
      resIcon: `${AWS4}.${icon}`,
      fill,
      stroke,
    },
  };
}

function shape(
  name: string,
  fill = "#527FFF",
  stroke = "none",
  dimensions?: Pick<SymbolDefinition, "widthScale" | "heightScale">,
): SymbolDefinition {
  return {
    role: "resource",
    drawio: { shape: `${AWS4}.${name}`, fill, stroke },
    ...dimensions,
  };
}

function group(
  fill: string,
  stroke: string,
  icon: string,
  fontColor: string,
  suppressBorder = false,
  dashed = false,
): SymbolDefinition {
  return {
    role: "container",
    drawio: {
      shape: `${AWS4}.group`,
      fill,
      stroke,
      styles: [
        `grIcon=${AWS4}.${icon}`,
        ...(suppressBorder ? ["grStroke=0"] : []),
        `fontColor=${fontColor}`,
        ...(dashed ? ["dashed=1"] : []),
      ],
    },
  };
}

// Catalog identifiers are kept as generic resources so new AWS4 icons work without
// adding repetitive definitions; specialized entries below override these defaults.
const catalogIcons = [
    "actuator",
    "alarm",
    "amazon_q",
    "amplify",
    "apache_mxnet",
    "api_gateway",
    "app2container",
    "app_mesh",
    "app_runner",
    "appflow",
    "application",
    "application_auto_scaling",
    "application_composer",
    "application_cost_profiler",
    "application_discovery_service",
    "application_load_balancer",
    "application_migration_service",
    "appstream",
    "appstream_20",
    "appsync",
    "archive",
    "artifact",
    "athena",
    "attribute",
    "attributes",
    "audit_manager",
    "augmented_ai",
    "aurora",
    "aurora_mysql_instance",
    "aurora_postgresql_instance",
    "auto_scaling2",
    "automation",
    "aws_cloud",
    "backup",
    "batch",
    "bedrock",
    "billing_conductor",
    "bottlerocket",
    "braket",
    "browser",
    "bucket",
    "bucket_with_objects",
    "budgets",
    "cache_node",
    "certificate_manager",
    "change_set",
    "chatbot",
    "chime",
    "chime_sdk",
    "classic_load_balancer",
    "clean_rooms",
    "client",
    "client_vpn",
    "cloud9",
    "cloud_development_kit",
    "cloud_map",
    "cloudformation",
    "cloudfront",
    "cloudhsm",
    "cloudsearch",
    "cloudshell",
    "cloudtrail",
    "cloudwatch",
    "cloudwatch_2",
    "cluster",
    "codeartifact",
    "codebuild",
    "codecatalyst",
    "codecommit",
    "codedeploy",
    "codeguru",
    "codeguru_profiler",
    "codeguru_reviewer",
    "codepipeline",
    "codestar",
    "codewhisperer",
    "cognito",
    "command_line_interface",
    "comprehend",
    "config",
    "connect",
    "connect_customer_profiles",
    "connect_voice_id",
    "connect_wisdom",
    "container_1",
    "container_2",
    "container_3",
    "control_tower",
    "corporate_data_center",
    "cost_and_usage_report",
    "cost_explorer",
    "crawler",
    "customer_gateway",
    "data_catalog",
    "data_center",
    "data_exchange",
    "data_pipeline",
    "database",
    "database_migration_service",
    "database_migration_workflow_job",
    "datasync",
    "datasync_agent",
    "datazone",
    "db_instance",
    "db_instance_read_replica",
    "db_instance_standby",
    "db_on_instance",
    "deadline_cloud",
    "deep_learning_amis",
    "deep_learning_containers",
    "deepcomposer",
    "deeplens",
    "deepracer",
    "dense_compute_node",
    "dense_storage_node",
    "deployment",
    "desired_state",
    "detective",
    "device_farm",
    "direct_connect",
    "directory_service",
    "disk",
    "documentdb",
    "download_distribution",
    "dynamodb",
    "ebs",
    "ec2",
    "ec2_image_builder",
    "ecr",
    "ecs",
    "ecs_task",
    "edge_location",
    "efs",
    "eks",
    "eks_anywhere",
    "eks_cloud",
    "elastic_beanstalk",
    "elastic_disaster_recovery",
    "elastic_fabric_adapter",
    "elastic_ip_address",
    "elastic_load_balancing",
    "elastic_network_adapter",
    "elastic_network_interface",
    "elastic_transcoder",
    "elasticache",
    "elasticache_for_memcached",
    "elasticache_for_redis",
    "elasticsearch_service",
    "elb",
    "elemental_appliances",
    "elemental_conductor",
    "elemental_delta",
    "elemental_link",
    "elemental_live",
    "elemental_server",
    "email_notification",
    "emr",
    "emr_engine",
    "emr_engine_mapr_m3",
    "emr_engine_mapr_m5",
    "emr_engine_mapr_m7",
    "endpoint",
    "endpoints",
    "entity_resolution",
    "event",
    "event_bus",
    "eventbridge",
    "eventbridge_pipes",
    "eventbridge_scheduler",
    "express_workflows",
    "external_sdk",
    "fargate",
    "fault_injection_service",
    "file_gateway",
    "file_system",
    "finspace",
    "firewall_manager",
    "flow_logs",
    "folder",
    "forecast",
    "forums",
    "fraud_detector",
    "freertos",
    "fsx",
    "fsx_for_lustre",
    "fsx_for_netapp_ontap",
    "fsx_for_openzfs",
    "fsx_for_windows_file_server",
    "gamelift",
    "gamesparks",
    "gateway_load_balancer",
    "general",
    "generic_database",
    "generic_firewall",
    "generic_sdk",
    "glacier",
    "global_accelerator",
    "global_secondary_index",
    "glue",
    "glue_databrew",
    "glue_elastic_views",
    "greengrass_connector",
    "ground_station",
    "guardduty",
    "hdfs_cluster",
    "healthlake",
    "honeycode",
    "hosted_zone",
    "http2_protocol",
    "http_notification",
    "http_protocol",
    "iam",
    "iam_identity_center",
    "identity_and_access_management",
    "illustration_desktop",
    "inspector",
    "instance2",
    "instance_with_cloudwatch2",
    "instances",
    "internet",
    "internet_2",
    "internet_gateway",
    "inventory",
    "iot_1click",
    "iot_action",
    "iot_analytics",
    "iot_analytics_channel",
    "iot_analytics_data_set",
    "iot_analytics_data_store",
    "iot_analytics_notebook",
    "iot_analytics_pipeline",
    "iot_button",
    "iot_certificate",
    "iot_core",
    "iot_device_defender",
    "iot_device_management",
    "iot_events",
    "iot_fleetwise",
    "iot_greengrass",
    "iot_hardware_board",
    "iot_policy",
    "iot_roborunner",
    "iot_rule",
    "iot_shadow",
    "iot_sitewise",
    "iot_things_graph",
    "iot_topic",
    "iot_twinmaker",
    "item",
    "items",
    "ivs",
    "kendra",
    "key_management_service",
    "keyspaces",
    "kinesis",
    "kinesis_data_analytics",
    "kinesis_data_firehose",
    "kinesis_data_streams",
    "kinesis_video_streams",
    "lake_formation",
    "lambda",
    "lambda_function",
    "laptop",
    "launch_wizard",
    "lex",
    "license_manager",
    "lightsail",
    "local_zones",
    "location_service",
    "logs",
    "lookout",
    "lookout_for_equipment",
    "lookout_for_metrics",
    "lookout_for_vision",
    "lumberyard",
    "machine_learning",
    "macie",
    "mainframe_modernization",
    "managed_blockchain",
    "managed_grafana",
    "managed_prometheus",
    "managed_workflows_apache_airflow",
    "management_console",
    "mariadb_instance",
    "mediaconnect",
    "mediaconvert",
    "medialive",
    "mediapackage",
    "mediastore",
    "mediatailor",
    "memorydb",
    "message",
    "metrics",
    "migration_hub",
    "migration_hub_orchestrator",
    "migration_hub_refactor_spaces",
    "mobile",
    "mobile_client",
    "monitron",
    "mq",
    "mqtt_protocol",
    "ms_sql_instance",
    "ms_sql_instance_alternate",
    "msk",
    "mysql_db_instance",
    "mysql_db_instance_alternate",
    "nat_gateway",
    "neptune",
    "network_access_control_list",
    "network_firewall",
    "network_load_balancer",
    "nice_dcv",
    "nimble_studio",
    "object",
    "office_building",
    "omics",
    "on_premises",
    "open_3d_engine",
    "opensearch",
    "opscenter",
    "opsworks",
    "optimized_instance",
    "oracle_db_instance",
    "oracle_db_instance_alternate",
    "organizations",
    "outposts",
    "panorama",
    "parallel_cluster",
    "parameter_store",
    "patch_manager",
    "peering",
    "permissions",
    "personal_health_dashboard",
    "personalize",
    "pinpoint",
    "piop",
    "polly",
    "postgresql_instance",
    "private_ca",
    "privatelink",
    "proton",
    "pytorch",
    "q_business",
    "q_developer",
    "qldb",
    "queue",
    "quicksight",
    "rds",
    "red_hat_openshift",
    "redshift",
    "rekognition",
    "reported_state",
    "rescue",
    "reserved_instance_reporting",
    "resilience_hub",
    "resource_access_manager",
    "resource_explorer",
    "robomaker",
    "robomaker_cloud_extension",
    "robomaker_development_environment",
    "robomaker_fleet_management",
    "robomaker_simulation",
    "role",
    "route_53",
    "route_table",
    "router",
    "rule",
    "run_command",
    "s3",
    "sagemaker",
    "sagemaker_ground_truth",
    "sagemaker_model",
    "sagemaker_notebook",
    "saml_token",
    "savings_plans",
    "schema_registry",
    "sdk",
    "search_documents",
    "secrets_manager",
    "security_hub",
    "security_lake",
    "sensor",
    "serverless_application_model",
    "service_catalog",
    "service_management_connector",
    "servo",
    "shield",
    "signer",
    "simple_email_service",
    "site_to_site_vpn",
    "snapshot",
    "snow_family",
    "snowball",
    "snowball_import_export",
    "snowcone",
    "snowmobile",
    "sns",
    "spot_instance",
    "sql_primary",
    "sql_replica",
    "sqs",
    "ssl_padlock",
    "stack",
    "state_manager",
    "step_functions",
    "storage_gateway",
    "streaming_distribution",
    "supply_chain",
    "systems_manager",
    "table",
    "tablet",
    "tape_gateway",
    "tape_storage",
    "template",
    "tensorflow",
    "textract",
    "timestream",
    "toolkit",
    "tools_and_sdks",
    "topic",
    "traditional_server",
    "transcribe",
    "transfer_family",
    "transit_gateway",
    "transit_gateway_attachment",
    "translate",
    "trusted_advisor",
    "user",
    "users",
    "vault",
    "verified_access",
    "verified_permissions",
    "vmware_cloud_on_aws",
    "volume",
    "volume_gateway",
    "vpc",
    "vpc_lattice",
    "vpn_connection",
    "vpn_gateway",
    "waf",
    "wavelength",
    "well_architected",
    "wickr",
    "workdocs",
    "workflow",
    "worklink",
    "workmail",
    "workspaces",
    "workspaces_web",
    "xray",
] as const;

const catalogIcons2025 = [
    "alexa_for_business",
    "ami",
    "api_gateway",
    "app2container",
    "app_mesh",
    "app_runner",
    "appconfig",
    "appflow",
    "application_composer",
    "application_discovery_service",
    "application_load_balancer",
    "application_migration_service",
    "appstream_2",
    "appsync",
    "archive",
    "artifact",
    "athena",
    "audit_manager",
    "augmented_ai",
    "aurora",
    "aurora_instance",
    "aurora_mysql_instance",
    "aurora_postgresql_instance",
    "auto_scaling",
    "auto_scaling2",
    "aws_cloud",
    "b2b_data_interchange",
    "backup",
    "batch",
    "bedrock",
    "bottlerocket",
    "bucket",
    "bucket_with_objects",
    "certificate_authority",
    "certificate_manager",
    "chatbot",
    "chime",
    "chime_sdk",
    "classic_load_balancer",
    "clean_rooms",
    "client",
    "client_vpn",
    "cloud9",
    "cloud_control_api",
    "cloud_development_kit",
    "cloud_directory",
    "cloud_map",
    "cloud_wan",
    "cloudendure_disaster_recovery",
    "cloudformation",
    "cloudformation_stack",
    "cloudformation_template",
    "cloudfront",
    "cloudhsm",
    "cloudsearch",
    "cloudshell",
    "cloudtrail",
    "cloudwatch",
    "cloudwatch_alarm",
    "cloudwatch_logs",
    "cloudwatch_rule",
    "codeartifact",
    "codebuild",
    "codecatalyst",
    "codecommit",
    "codedeploy",
    "codeguru",
    "codepipeline",
    "codestar",
    "codewhisperer",
    "cognito",
    "command_line_interface",
    "comprehend",
    "compute_optimizer",
    "config",
    "connect",
    "control_tower",
    "corporate_data_center",
    "corretto",
    "customer_gateway",
    "data_exchange",
    "data_firehose",
    "data_pipeline",
    "database_migration_service",
    "datasync",
    "datasync_agent",
    "datazone",
    "deadline_cloud",
    "deepcomposer",
    "deeplens",
    "deepracer",
    "detective",
    "devops_guru",
    "direct_connect",
    "direct_connect_gateway",
    "directory_service",
    "disk",
    "documentdb",
    "dynamodb",
    "dynamodb_accelerator",
    "dynamodb_attribute",
    "dynamodb_attributes",
    "dynamodb_global_secondary_index",
    "dynamodb_item",
    "dynamodb_items",
    "dynamodb_stream",
    "dynamodb_table",
    "ec2",
    "ecr",
    "ecr_image",
    "ecr_registry",
    "ecs",
    "ecs_container1",
    "ecs_service",
    "ecs_task",
    "eks",
    "eks_anywhere",
    "eks_cloud",
    "eks_distro",
    "eks_pod",
    "elastic_beanstalk",
    "elastic_block_store",
    "elastic_disaster_recovery",
    "elastic_fabric_adapter",
    "elastic_file_system",
    "elastic_ip",
    "elastic_load_balancing",
    "elastic_transcoder",
    "elasticache",
    "elasticache_for_memcached",
    "elasticache_for_redis",
    "elemental_mediaconnect",
    "elemental_mediaconvert",
    "elemental_medialive",
    "elemental_mediapackage",
    "elemental_mediastore",
    "elemental_mediatailor",
    "emr",
    "endpoints",
    "entity_resolution",
    "eventbridge",
    "eventbridge_schema_registry",
    "fargate",
    "fault_injection_service",
    "file_cache",
    "file_system",
    "finspace",
    "firewall_manager",
    "forecast",
    "forums",
    "fraud_detector",
    "freertos",
    "fsx",
    "fsx_for_lustre",
    "fsx_for_netapp_ontap",
    "fsx_for_openzfs",
    "fsx_for_wfs",
    "gateway_load_balancer",
    "general",
    "generic_database",
    "glacier",
    "global_accelerator",
    "glue",
    "glue_databrew",
    "glue_elastic_views",
    "guardduty",
    "health_dashboard",
    "healthlake",
    "healthscribe",
    "honeycode",
    "iam",
    "iam_identity_center",
    "inspector",
    "instance",
    "instances",
    "interactive_video_service",
    "internet",
    "internet_gateway",
    "iot",
    "iot_analytics",
    "iot_button",
    "iot_core",
    "iot_device_defender",
    "iot_device_management",
    "iot_events",
    "iot_expresslink",
    "iot_fleetwise",
    "iot_greengrass",
    "iot_sitewise",
    "iot_twinmaker",
    "ivs_chat",
    "kendra",
    "key_management_service",
    "keyspaces",
    "kinesis",
    "kinesis_data_analytics",
    "kinesis_data_streams",
    "kinesis_video_streams",
    "lake_formation",
    "lambda",
    "lambda_function",
    "lex",
    "license_manager",
    "lightsail",
    "local_zones",
    "lookout_equipment",
    "lookout_metrics",
    "lookout_vision",
    "machine_learning",
    "macie",
    "mainframe_modernization",
    "managed_flink",
    "managed_grafana",
    "managed_prometheus",
    "managed_streaming_kafka",
    "managed_workflows_apache_airflow",
    "management_console",
    "memorydb_for_redis",
    "migration_evaluator",
    "migration_hub",
    "mobile_client",
    "monitron",
    "mq",
    "multimedia",
    "multiple_volumes",
    "nat_gateway",
    "neptune",
    "network_firewall",
    "network_load_balancer",
    "neuron",
    "nice_dcv",
    "nimble_studio",
    "object",
    "office_building",
    "omics",
    "opensearch",
    "opsworks",
    "organizations",
    "outposts",
    "outposts_1u_2u",
    "outposts_rack",
    "panorama",
    "parallel_cluster",
    "payment_cryptography",
    "peering",
    "permissions",
    "personal_health_dashboard",
    "personalize",
    "pinpoint",
    "polly",
    "private_5g",
    "privatelink",
    "proton",
    "pytorch",
    "q",
    "q_business",
    "quicksight",
    "rds",
    "rds_instance",
    "rds_mariadb_instance",
    "rds_multi_az",
    "rds_mysql_instance",
    "rds_oracle_instance",
    "rds_postgresql_instance",
    "rds_proxy",
    "rds_sql_server_instance",
    "red_hat_openshift",
    "redshift",
    "rekognition",
    "rescue",
    "resilience_hub",
    "resource_access_manager",
    "resource_explorer",
    "role",
    "route_53",
    "route_53_hosted_zone",
    "router",
    "s3",
    "s3_express_one_zone",
    "saas",
    "sagemaker",
    "sdk",
    "secrets_manager",
    "security_hub",
    "security_lake",
    "server_migration_service",
    "serverless_application_repository",
    "service_catalog",
    "ses",
    "shield",
    "shield_advanced",
    "signer",
    "simspace_weaver",
    "site_to_site_vpn",
    "snapshot",
    "snow_family",
    "snowball",
    "snowball_edge",
    "snowcone",
    "snowmobile",
    "sns",
    "spot_instance",
    "sqs",
    "ssl_padlock",
    "step_functions",
    "storage_gateway",
    "systems_manager",
    "tape_storage",
    "tensorflow",
    "textract",
    "timestream",
    "titan",
    "tools_and_sdks",
    "traditional_server",
    "trainium",
    "transcribe",
    "transfer_family",
    "transit_gateway",
    "translate",
    "trusted_advisor",
    "user",
    "users",
    "vault",
    "verified_access",
    "verified_permissions",
    "virtual_private_cloud_vpc",
    "vmware_cloud_on_aws",
    "volume",
    "vpc",
    "vpn_connection",
    "vpn_gateway",
    "waf",
    "wavelength",
    "well_architected_tool",
    "wickr",
    "workdocs",
    "worklink",
    "workmail",
    "workspaces",
    "workspaces_family",
    "workspaces_personal",
    "workspaces_pools",
    "workspaces_secure_browser",
    "workspaces_thin_client",
    "workspaces_web",
    "xray",
] as const;

const standaloneIcons = new Set([
  "client",
  "corporate_data_center",
  "internet",
  "mobile_client",
  "traditional_server",
  "user",
  "users",
]);
const catalogSymbols: Record<string, SymbolDefinition> = Object.fromEntries(
  [...catalogIcons, ...catalogIcons2025].map((icon) => [icon, standaloneIcons.has(icon) ? shape(icon, "#232F3D") : resource(icon)]),
);

const symbols: Record<string, SymbolDefinition> = {
    ...catalogSymbols,
  cloud: group("none", "#232F3E", "group_aws_cloud_alt", "#232F3E"),
  vpc: group("none", "#8C4FFF", "group_vpc2", "#AAB7B8"),
  subnet: group("#E6F6F7", "#00A4A6", "group_security_group", "#147EBA", true),
  private_subnet: group(
    "#E6F6F7",
    "#00A4A6",
    "group_security_group",
    "#147EBA",
    true,
  ),
  public_subnet: group(
    "#F2F6E8",
    "#7AA116",
    "group_security_group",
    "#248814",
    true,
  ),
  az: group("none", "#147EBA", "group_availability_zone", "#147EBA"),
  region: group("none", "#00A4A6", "group_region", "#147EBA", false, true),
  internet: shape("internet", "#232F3D", "none", {
    widthScale: 1,
    heightScale: 0.6,
  }),
  apigateway: resource("api_gateway", "#E7157B"),
  app_config: resource("app_config", "#E7157B"),
  alb: shape("application_load_balancer", "#8C4FFF"),
  aoss: resource("elasticsearch_service"),
  backup: resource("backup", "#277116"),
  certificate_manager_2: shape("certificate_manager_2", "#BF0816"),
  certificate_manager_3: resource("certificate_manager_3", "#C7131F"),
  client_vpn: resource("client_vpn", "#5A30B5"),
  cloudfront: resource("cloudfront", "#8C4FFF"),
  cloudhsm: resource("cloudhsm", "#C7131F"),
  cloudtrail: resource("cloudtrail", "#BC1356"),
  cloudwatch_2: resource("cloudwatch_2", "#BC1356"),
  dynamodb: resource("dynamodb", "#C925D1"),
  ec2: resource("ec2"),
  ecr: resource("ecr", "#ED7100"),
  ecs: resource("ecs", "#ED7100"),
  eks: resource("eks"),
  elb: resource("elastic_load_balancing"),
  elasticsearch_service: resource("elasticsearch_service", "#8C4FFF"),
  eni: shape("elastic_network_interface", "#8C4FFF"),
  endpoint: shape("endpoint", "#4D27AA"),
  eventbridge: resource("eventbridge", "#E7157B"),
  general: shape("general", "#232F3D"),
  generic_firewall: shape("generic_firewall", "#232F3E"),
  guardduty: resource("guardduty", "#DD344C"),
  iam: resource("identity_and_access_management"),
  inspector: resource("inspector", "#C7131F"),
  internetgateway: shape("internet_gateway", "#8C4FFF"),
  key_management_service: resource("key_management_service", "#C7131F"),
  kinesis_data_stream: resource("kinesis_data_streams", "#8C4FFF"),
  lambda: resource("lambda", "#ED7100"),
  natgateway: shape("nat_gateway", "#8C4FFF"),
  network_firewall_endpoints: shape("network_firewall_endpoints", "#DD344C"),
  networkfirewall: resource("network_firewall", "#DD344C"),
  nlb: shape("network_load_balancer", "#8C4FFF"),
  rds: resource("rds"),
  role: shape("role", "#DD344C"),
  route53: resource("route_53", "#5A30B5"),
  route_53_resolver: shape("route_53_resolver", "#4D27AA"),
  s3: resource("s3", "#7AA116"),
  secretsmanager: resource("secrets_manager", "#C7131F"),
  security_hub: resource("security_hub", "#C7131F"),
  ses: resource("simple_email_service", "#3334B9"),
  shield: resource("shield_shield_advanced", "#DD344C"),
  simple_email_service: resource("simple_email_service", "#3334B9"),
  sns: resource("sns", "#E7157B"),
  sqs: resource("sqs", "#E7157B"),
  stepfunctions: resource("step_functions"),
  tgw: resource("transit_gateway"),
  tgwa: shape("transit_gateway_attachment", "#8C4FFF"),
  vpcendpoint: shape("endpoints", "#8C4FFF"),
  waf: resource("waf", "#DD344C"),
};

export const awsProvider: SymbolProvider = {
  namespace: "aws",
  symbols,
  aliases: {
    apigw: "apigateway",
    igw: "internetgateway",
    internet_gateway: "internetgateway",
    kinesis: "kinesis_data_stream",
    kinesisdatastream: "kinesis_data_stream",
    kinesis_data_streams: "kinesis_data_stream",
    nat: "natgateway",
    nat_gateway: "natgateway",
    networkloadbalancer: "nlb",
    network_load_balancer: "nlb",
    transitgateway: "tgw",
    transit_gateway: "tgw",
    transitgatewayattachment: "tgwa",
    transit_gateway_attachment: "tgwa",
    vpce: "vpcendpoint",
  },
};
